#!/bin/bash

echo "Simple HDD benchmark (dd based)"
echo "--------"
echo "Tests copied from"
echo "https://www.thomas-krenn.com/en/wiki/Linux_I/O_Performance_Tests_using_dd"
echo " ======================================================================="
echo " "
echo "Starting..."
echo " "

echo "==Throughput=="
echo "1GB was written for the test"
echo "Typical Laptop: 1073741824 bytes (1.1 GB) copied, 32.474 s, 33.1 MB/s"
echo "Typical VPS: 1073741824 bytes (1.1 GB) copied, 9.94862 s, 108 MB/s"
testfile1=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
sudo dd if=/dev/zero of=/root/$testfile1 bs=1G count=1 oflag=direct
sleep 2
echo "---"
echo " "


echo "==Latency=="
echo "512KB was written for the test"
echo "Typical Laptop: 512000 bytes (512 kB) copied, 0.36084 s, 1.4 MB/s"
echo "Typical VPS: 512000 bytes (512 kB) copied, 0.812216 s, 630 kB/s"
testfile2=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
sudo dd if=/dev/zero of=/root/$testfile2 bs=512 count=1000 oflag=direct
sleep 2
echo "---"
echo " "